name: Bug Report
description: Create a bug report to help us improve.
title: '[issue summary] Please verify version before submitting new issue'
projects: []
body:
  - type: input
    id: version
    attributes:
      label: Which version of [namespace]-[name] do you have installed?
  - type: markdown
    attributes:
      value: >
        The current released version of [namespace]-[name] is [![See it on
        NPM!](https://img.shields.io/npm/v/@aurodesignsystem/[namespace]-[name]?style=for-the-badge&color=orange)](https://www.npmjs.com/package/@aurodesignsystem/[namespace]-[name])
  - type: dropdown
    id: browsers
    attributes:
      label: What browser client(s) are you seeing the issue on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: platform
    attributes:
      label: What devices(s) are you seeing the issue on?
      multiple: true
      options:
        - Desktop
        - Mobile
  - type: textarea
    id: details
    attributes:
      label: Steps to reproduce
      description: List out the steps to reproduce the behavior and include screenshots
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        
        Result:
        '... What happened that you didn't expect? ...'
  - type: checkboxes
    id: repro
    attributes:
      label: Reproducible on the [Auro doc site](https://auro.alaskaair.com/)?
      description: Are you able to reproduce the issue on the Auro doc site?
      options:
        - Yes
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Please add a clear and concise description of what you expected to
        happen.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.