name: Release Workflow

on:
  push:
    branches:
      - 'rc/**'
      - 'main'
  workflow_dispatch:

jobs:
  action:
    uses: AlaskaAirlines/auro-actions/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: $\{{ secrets.NPM_TOKEN }}
    with:
      cache-dirs: |
        ./components/**/dist
        ./components/**/demo
        ./components/**/node_modules
        ./node_modules
        ./custom-elements.json
        ./apps/**/node_modules
        ./apps/svelte-framework/.svelte-kit